firebolt-db/firebolt-python-sdk

- src/firebolt/async_db/connection.py
- src/firebolt/async_db/cursor.py
- src/firebolt/async_db/util.py
- src/firebolt/common/exception.py
- src/firebolt/common/urls.py
- src/firebolt/service/engine.py
- tests/unit/async_db/test_connection.py
- tests/unit/async_db/test_cursor.py
- tests/unit/conftest.py
In order to ease new client sdk integration I'm improving the error messages the users are likely to get on failed connection.
This reduces the need to reach out to us when something fails and allows for faster user feedback if something that's controlled by them is incorrect (e.g. database name is mistyped or engine is not running).
> Fir 9113: better error messages

- .github/workflows/python-app.yml
Ref: https://github.com/marketplace/actions/convetional-commits-pull-request
This action will validate PR title and post a comment if it does not pass the tests. If title is modified it reruns to validate and if everything's ok the comment will be removed. 
Example of alternatives considered:
https://github.com/ptiurin/integration-testing-setup/pull/2
However, I believe the current one looks and explains what's breaking better.
> ci: FIR9441 Adding PR title validation

- src/firebolt/client/constants.py
- src/firebolt/service/manager.py
Increased ResourceManager operations timeout from 5 seconds to 2 minutes.
This is required for integration tests since they fail with ReadTimeout error from time to time
> fix: increase timeout for resource manager operations

- setup.cfg
This setting allows mypy checks in packages that use firebolt-sdk.
> build: typed option in setup.cfg

- CONTRIBUTING.MD
Adding this to explain to the future contributors what they can expect making a PR.
> docs: Adding pull request guidelines

- src/firebolt/db/connection.py
Apparently, I've finally managed to investigate the issue with `RuntimeWarning: coroutine 'BaseConnection._aclose' was never awaited` in tests.
It seems like `connection.__del__` function (which inside calls asynchronous `_aclose` in global event loop) sometimes gets called after the event loop is closed (because it's called by the garbage collector in background). To fix this, added a custom loop for connection to use it for closing. I assume this issue could happen in real environments too.
> fix: add custom loop for connection __del__

- src/firebolt/async_db/_types.py
- src/firebolt/db/connection.py
- tests/integration/dbapi/conftest.py
- tests/integration/dbapi/sync/conftest.py
- tests/integration/dbapi/sync/test_errors.py
- tests/unit/db/test_connection.py
- tests/unit/service/test_engine.py
Removed `Connection.close` call from connection finalizer. This simplifies `Connection` class itself and exposes workflows where connections are not closed. Despite closing, finalizer will check if connection is closed on delete and will raise a warning if not.
Improved unit and integration tests to get rid of all not closed connections.
Also, this PR contains a fix for integration tests. It seems like type system has slightly changed for firebolt recently. For example, `-30000` is now treated as `Int16`, while it used to be `Int32`. Updated tests cases respectively
> feat: No automatic close

- src/firebolt/common/util.py
- tests/unit/common/test_util.py
Add tests for `async_to_sync` function, since it's been flaky for recently.
Also, added a real case of using `async_to_sync` with `asyncio.run`, which cased an error. Fixed the error
> fix: async_to_sync tests

- tests/integration/dbapi/async/test_queries_async.py
- tests/integration/dbapi/sync/test_queries.py
Temporary disabled long running integration tests until we figure out what's wrong with it.
This tests was doing insert and than select which checked inserted data. We still run a single insert query now but do not check the data.
> test: temporary disable long running integration tests

- src/firebolt/async_db/__init__.py
- src/firebolt/db/__init__.py
- tests/unit/async_db/test_module.py
- tests/unit/conftest.py
- tests/unit/db/test_module.py
Exposing dbapi exceptions on firebolt.db and firebolt.async_db level. This conforms to PEP-249 and simplifies SQLAlchemy connector design.
> refactor: Exposing exceptions on module level

- .github/workflows/integration-tests.yml
- .github/workflows/release.yml
Secrets have to be explicitly passed down to the integration test workflow on call.
> ci: Passing secrets on release action

- src/firebolt/async_db/connection.py
- src/firebolt/async_db/cursor.py
- tests/integration/dbapi/async/test_queries_async.py
- tests/integration/dbapi/sync/test_queries.py
- tests/unit/async_db/test_connection.py
- tests/unit/async_db/test_cursor.py
- tests/unit/db/test_connection.py
- tests/unit/db/test_cursor.py
Improvements for PEP-249 conformance
- Added `connection.commit` method with void functionality
- Raise `DataError` when no data was returned from query
closes #74
> feat: implement Connection.commit, DataError on empty data fetch

- src/firebolt/async_db/cursor.py
- tests/unit/async_db/test_cursor.py
- tests/unit/db/test_cursor.py
Since we currently don't support parameterized sql queries, raise an error if one is being executed
> fix: raise NotSupportedError for parametierized queries

- src/firebolt/common/util.py
Set global loop to new if it's empty instead of opening and closing a new one each time
> fix: Asyncio set global loop

- src/firebolt/async_db/_types.py
- src/firebolt/async_db/cursor.py
- tests/integration/dbapi/async/test_queries_async.py
- tests/integration/dbapi/sync/test_queries.py
- tests/unit/async_db/test_cursor.py
- tests/unit/async_db/test_typing_format.py
- tests/unit/db/test_cursor.py
Implemented multi-statement queries functionality based on the design
https://docs.google.com/document/d/13O5jHFjnvRrNSvzBXNohYYz4ChI1jhi_7xyIwd1_7Xs/edit
- Added `nextset` method from PEP249 to be able to move to next result set
- Set `cursor.state` to new `CursorState.ERROR` value if error occured during query execution. This allows to figure out if all queries have passed in case of multi-statement, and is more verbose in my opinion
Added unit and integration tests
> feat: Fir 8425 implement multi statement funct

- setup.cfg
- tests/unit/async_db/conftest.py
- tests/unit/async_db/test_cursor.py
- tests/unit/client/conftest.py
- tests/unit/client/test_auth.py
- tests/unit/conftest.py
- tests/unit/db/conftest.py
- tests/unit/db/test_cursor.py
- tests/unit/service/conftest.py
Upgrading `httpx` to the latest version. `pytest-httpx` also needed to be updated. API has changed slightly between those versions, most notably `to_response` is deprecated in favour of `httpx.Response` also pytest-httpx no longer accepts as equal  `<url>/?database=<db>` and `<url>?database=<db>`.
From quick research looks like slash first is generally accepted so I modified `query_url` mock to reflect that. This does not affect the actual execution (confirmed in integration testing) and is purely mock-related.
This PR is a prerequisite to fixing the TCP timeout.
> chore: Bump httpx to 0.21.3

- .github/workflows/code-check.yml
- .pre-commit-config.yaml
- setup.cfg
Added mypy check as a part of pre-commit hooks. Therefore, removed mypy step from code-check workflow
> ci: Add mypy pre-commit hook

- src/firebolt/async_db/cursor.py
- src/firebolt/db/cursor.py
- tests/integration/dbapi/async/test_queries_async.py
- tests/integration/dbapi/sync/test_queries.py
- tests/unit/async_db/test_cursor.py
- tests/unit/db/test_cursor.py
Hotfix for multi-statement queries. Idx wasn't set to 0 so some queries results were incorrect.
> fix: Multistatement fix idx

- src/firebolt/async_db/connection.py
TCP_KEEPIDLE is not available on MacOS. TCP_KEEPALIVE is the alternative, however it's not added to the `socket` library until Python 3.10. This is a workaround.
Tested locally on a mac.
> fix: MacOS keepalive setting

- examples/dbapi.ipynb
- src/firebolt/async_db/connection.py
- src/firebolt/common/util.py
- src/firebolt/db/connection.py
- src/firebolt/db/cursor.py
- tests/unit/common/test_util.py
Fixed jupyter notebook async issues, extended dbapi jupyter examples.
This fix also add's an ability to use sync connection and cursor inside an asyncio loop, which we didn't support previously.
The issue was that basically loops can't be nested in asyncio, and all jupyter code is run inside a loop. The workaround for this is to create a thread inside a running loop and use new loop there. One problem is that a single `httpx.AsyncClient` should use the same loop always, so connection needs to cache it, which is done by storing `AsyncJobThread`
> fix: Jupyter runtime

- src/firebolt/model/engine.py
- src/firebolt/service/engine.py
- tests/unit/service/conftest.py
- tests/unit/service/test_engine.py
Allowing special parameters like `db_version`, `proxy_version` which are part of the API, but should be obfuscated from the external user. As discussed we're fine if users find out about them via reading the code, but reading the docs should not give hints about their existence.
This will mainly be used for automated testing by internal teams.
> feat(FIR-10892): Internal args for engine

- setup.cfg
- src/firebolt/common/token_storage.py
According to cryptograpy 3.1 changelog
```
**backend** arguments to functions are no longer required and the default backend will automatically be selected if no backend is provided.
```
In order to be compatible with cryptography 2.8, required by Redash, we should provide default backend as an argument
> fix: Compatibility with cryptography 2.*

- src/firebolt/async_db/connection.py
- src/firebolt/common/urls.py
- tests/integration/dbapi/async/conftest.py
- tests/integration/dbapi/async/test_queries_async.py
- tests/integration/dbapi/sync/conftest.py
- tests/integration/dbapi/sync/test_queries.py
- tests/unit/async_db/test_connection.py
- tests/unit/conftest.py
- tests/unit/db/test_connection.py
Allow users to skip engine parameter. Get default engine url in this case.
Added unit and integration tests
> feat: Fir 12126 make engine parameter optional

- .github/workflows/nightly.yml
- tests/integration/resource_manager/test_engine.py
Fixed nightly resource manager tests. The issue was that engine name wasn't unique when it was being created.
Used database_name to make it unique
Added security scans to nightly job
> ci: Fir 12453 add security scans to nightly 

- .github/workflows/code-check.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pull-request.yml
- .github/workflows/unit-tests.yml
- README.md
Adding CI badges to indicate code quality standards to repo contributors. 
Coverage is extracted from the report, uploaded to a gist, which is then referenced in the Readme. This ensures there's no need to commit an update to the readme to see the coverage changing.
> docs(FIR-12444): Add CI badges to readme

- .github/workflows/nightly.yml
Since the addition of readme badges nightly has been broken. Unit-test workflow needs a GIST_PAT secret. Adding it to resolve the error.
> ci: Add unit-test secret to nightly

- src/firebolt/async_db/connection.py
- src/firebolt/client/auth.py
- src/firebolt/common/settings.py
- src/firebolt/model/engine.py
- src/firebolt/service/manager.py
- tests/unit/async_db/test_connection.py
- tests/unit/client/test_auth.py
- tests/unit/conftest.py
- tests/unit/db/test_connection.py
- tests/unit/service/test_resource_manager.py
Added ability to disable token caching.
It now could be disabled with`use_token_cache=False`, provided as a `connect` function argument or as a `Settings` field.
Added unit tests
> feat: Fir 12879 allow skipping token caching

- src/firebolt/async_db/cursor.py
- src/firebolt/db/cursor.py
- tests/unit/async_db/test_cursor.py
- tests/unit/db/test_cursor.py
Allow users to skip query parsing by providing `skip_parsing` parameter to `execute` method
> perf: Fir 13517 allow skipping query parsing i

- tests/integration/utils/test_usage_tracker.py
Making sure the directory is clean before creating it again. This fixes running integration tests after a failure.
> fix: Clean temp test directory

- .github/workflows/integration-tests.yml
- tests/integration/utils/test_usage_tracker.py
Making sure all tracker tests execute in the same process, if run in parallel.
> fix: Sync execution of tracker tests

- setup.cfg
New release of pytest-asyncio is breaking our unit tests on python `3.*.12` and `3.*.13`. Pinning it for now.
> build: Pin dev pytest-asyncio version

- tests/integration/dbapi/conftest.py
Due to a change in dev we can no longer use `int8` as a column. I'm renaming it to fix the tests.
> ci: Escape reserved column name

- setup.cfg
- tests/integration/dbapi/async/test_auth_async.py
- tests/integration/dbapi/async/test_errors_async.py
- tests/integration/dbapi/async/test_queries_async.py
- tests/unit/async_db/test_connection.py
- tests/unit/async_db/test_cursor.py
- tests/unit/client/auth/test_auth_async.py
- tests/unit/client/test_client_async.py
- tests/unit/common/test_util.py
Set the `asyncio_mode` to `auto` in `setup.cfg` and removed all `@pytest.mark.asyncio` decorators. All tests still pass.
> fix: Set asyncio_mode to deal with asyncio deprecation warnings

- src/firebolt/async_db/_types.py
SQLAlchemy needs this to correctly work with additional types
https://github.com/firebolt-db/firebolt-sqlalchemy/pull/64 depends on it
> feat: Type object hashing

- tests/integration/conftest.py
- tests/integration/dbapi/async/conftest.py
- tests/integration/dbapi/async/test_auth_async.py
- tests/integration/dbapi/async/test_errors_async.py
- tests/integration/dbapi/sync/conftest.py
- tests/integration/dbapi/sync/test_auth.py
- tests/integration/dbapi/sync/test_errors.py
- tests/integration/dbapi/sync/test_queries.py
Using service account for CI leads to less errors from the backend and avoids being blocked by the rate limiter.
Removing `test_invalid_credentials` since the same functionality is tested in `test_credentials_invalidation`
Functionality is confirmed by running integration test workflow on this branch.
> ci: Using service account

- setup.cfg
Relaxing pydantic to be more inclusive. This helps current Airbyte integration.
I've tested the sdk with 1.8.0 as well as 1.9.2
> build: Relax pydantic version

- .github/workflows/integration-tests.yml
- .github/workflows/nightly.yml
- tests/integration/dbapi/async/conftest.py
- tests/integration/dbapi/async/test_auth_async.py
- tests/integration/dbapi/async/test_errors_async.py
- tests/integration/dbapi/sync/conftest.py
- tests/integration/dbapi/sync/test_auth.py
- tests/integration/dbapi/sync/test_errors.py
- tests/integration/dbapi/sync/test_queries.py
It is the only solution to fix our tests so far.
Tested this by running integration tests from this branch.
> ci: Switch back to username password auth

- README.md
- src/firebolt/async_db/__init__.py
- src/firebolt/db/__init__.py
As a recent issue showed, sharing a cursor in a multi-threaded environment is not safe. The issue stems from asyncio not playing nicely in such environment. Moreover, this also leads to a confusion on query result retention - if several queries run at the same time it's not deterministic which query's result will be stored (also its success status). Therefore the best practice is not to share cursors at all.
> docs: Clarify thread safety

- setup.cfg
- src/firebolt/async_db/cursor.py
- src/firebolt/db/connection.py
- src/firebolt/db/cursor.py
- src/firebolt/utils/util.py
- tests/integration/dbapi/sync/test_queries.py
Asyncio prevents us from sharing Connection objects across threads due to registering httpx Client to the main thread's loop.  Trio seems to solve this problem, as confirmed in the integration test I've added. Looks like there's no impact on the rest of the functionality.
> feat: use trio for async_to_sync

- tests/integration/conftest.py
- tests/integration/dbapi/sync/conftest.py
- tests/integration/dbapi/sync/test_system_engine.py
Testing compatibility with the system engine
> test: System engine checks

- setup.cfg
Currently the latest version of anyio does not support trio 0.22.0 and raises warnings. In order to reduce the verbosity of our sdk I'm limiting trio to 0.21.0. This does not affect any of the sdk functions, as confirmed by the integration tests.
More info in https://packboard.atlassian.net/browse/FIR-17043
> build: limit Trio version

- tests/integration/dbapi/async/test_queries_async.py
- tests/integration/dbapi/sync/test_queries.py
- tests/integration/dbapi/sync/test_system_engine.py
Made a couple of changes in order to fix integration tests
- removed outdated `firebolt_use_decimal` flag. This seems to be the default behavior now
- remove `select 1` from expected to fail statements for system engine. System engine seems to support this statements now
The last integration tests run was successful: https://github.com/firebolt-db/firebolt-python-sdk/actions/runs/3901616576
> test: Fix integration tests

- .github/workflows/unit-tests.yml
Removing deprecated parameter in favour of new way of setting it https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> ci(FIR-16394): Remove set output

- setup.cfg
- src/firebolt/common/settings.py
- src/firebolt/model/database.py
- src/firebolt/model/engine.py
- src/firebolt/model/engine_revision.py
- src/firebolt/service/manager.py
Released `pydantic` version to allow `>=1.10` (https://github.com/firebolt-db/firebolt-python-sdk/issues/227)
Added some changes to field definitions in order to support it
> chore: Relax pydantic version

- src/firebolt/client/resource_manager_hooks.py
- tests/unit/client/test_client.py
Fixed cached token refresh on 401 issue
> fix: Fir 14945 fix cached token refresh

- src/firebolt/async_db/_types.py
`__name__` attribute is used in DBT to map python class to SQL query.
This is needed for https://github.com/firebolt-db/dbt-firebolt/pull/95
> fix: Decimal class type compatibility

- .github/workflows/code-check.yml
- .pre-commit-config.yaml
- src/firebolt/async_db/cursor.py
- tests/integration/dbapi/conftest.py
- tests/integration/dbapi/sync/test_system_engine.py
There's been a recent change in reserved keywords. We need to fix our CI:
https://github.com/firebolt-db/firebolt-python-sdk/actions/runs/4251261890
Also fixing pre-commit
> ci: Fix escaping keywords

- src/firebolt/async_db/_types.py
- tests/integration/dbapi/async/test_queries_async.py
- tests/integration/dbapi/conftest.py
- tests/integration/dbapi/sync/test_queries.py
- tests/unit/async_db/conftest.py
- tests/unit/async_db/test_typing_format.py
- tests/unit/async_db/test_typing_parse.py
- tests/unit/db_conftest.py
Added support for bytea type (both parsing and formatting)
> feat: Fir 16953 bytea support

- src/firebolt/async_db/cursor.py
- tests/integration/dbapi/async/test_queries_async.py
- tests/integration/dbapi/sync/test_queries.py
With the latest changes to aragog API behaviour has changed. Modifying our tests to account for it.
> test: Fix insert rowcount

- src/firebolt/service/binding.py
We do useless api call on `get_attached_engines` to fetch engine info if no engines are bound to a database. This avoids this call returning an empty list straight away.
A call with no engines also breaks now with the recent changes to the API so this also fixes the issue we're having in nightlies.
> fix(ResourceManager): no engines attached to db

- src/firebolt/async_db/_types.py
- tests/unit/async_db/test_typing_format.py
Fixed parsing of statements, specifically false positive recognition of set statements.
Also added support for query_parameters set statements, like `query_parameters={"name":"param1","value":"Hello, world!"}`
> fix: improve set statements parsing

- .github/workflows/integration-tests.yml
- .github/workflows/unit-tests.yml
- setup.cfg
- tests/unit/conftest.py
Allure adds a nice graphical interface to our tests to allow better overview of failures. UI is easier to navigate than the log dump in github and grouping of tests by failure type is invaluable. Logs are also split and shown per test.
This also lets us view performance changes over time.
Reported to PR/commit via Checks:
Implemented using composite action https://github.com/firebolt-db/action-allure-report
> ci: Allure integration for tests

- tests/integration/dbapi/async/test_queries_async.py
- tests/integration/dbapi/sync/test_queries.py
Create/drop queries no longer return a body. Reflecting this in tests.
> test: Fix rowcount tests

- src/firebolt/async_db/connection.py
- src/firebolt/db/connection.py
socket options were added recently, maybe one day they will allow us to avoid the tcp hack.
For now, httpx does not use this parameter. 
I'm changing the hack to be compatible with both versions, with and without the additional options. We're not using them anyway.
> build: new httpcore backwards compatibility

- tests/integration/dbapi/async/test_queries_async.py
- tests/integration/dbapi/sync/test_queries.py
> test: No rowcount check on DDL

- docsrc/Connecting_and_queries.rst
Add context manager to connection example
> docs: Update Connecting_and_queries.rst

- src/firebolt/common/base_cursor.py
- src/firebolt/db/connection.py
- src/firebolt/db/cursor.py
- tests/unit/async_db/test_connection.py
- tests/unit/async_db/test_cursor.py
- tests/unit/db/conftest.py
- tests/unit/db/test_connection.py
- tests/unit/db/test_cursor.py
- tests/unit/db/test_util.py
- tests/unit/db_conftest.py
Improving test coverage in preparation for mutation test CI.
> test: Additional tests to satisfy mutation testing

- setup.cfg
- src/firebolt/async_db/connection.py
- src/firebolt/async_db/cursor.py
- src/firebolt/client/auth/base.py
- src/firebolt/common/base_cursor.py
- src/firebolt/utils/util.py
added a timer option that counts the time of Authentication, Resolving engine name, Running query and Parsing query output. the info will be written on the log if an env variable named `FIREBOLT_SDK_PERFORMANCE_DEBUG` will be equal to 1
> feat: Performance debug info

- src/firebolt/async_db/util.py
- src/firebolt/db/util.py
- src/firebolt/utils/urls.py
- tests/unit/db_conftest.py
Removed `/dynamic/query` path from system engine url
> fix: remove dynamic/query path from system engine url

- .github/workflows/integration-tests.yml
It may accidentally expose the password when a test fails. We need to rethink this approach.
> ci: Remove Allure from integration tests

- README.md
- examples/dbapi.ipynb
- examples/management.ipynb
> docs: Update new identity documenation in repo

- tests/integration/conftest.py
Related to FIR-25360 and the underlying issue of not escaping passwords.
Github automatically replaces those with **** but we should do it regardless. This allows us to re-enable allure again.
Verified locally with an artificially failing test that uses password fixture. It no longer appeared in the logs or in allure report.
> test: Safe printing of secrets

- docsrc/Connecting_and_queries.rst
- setup.cfg
- src/firebolt/async_db/cursor.py
- src/firebolt/client/auth/base.py
- tests/unit/client/test_client_async.py
This lock is not necessary as cursor object should not be shared across threads. Even if it is, either with or without locking the result would be unexpected.
> fix: Remove redundant lock

- setup.cfg
Anyio had a 4.0 release recently that affects internal API. We happen to use it in order to avoid a race condition. I'm limiting anyio to below 4.0 to avoid it. We can revisit the code affected, but at the moment I don't see an alternative API we can use.
This breaks on import when anyio 4.0 is installed: https://github.com/firebolt-db/firebolt-python-sdk/blob/0.x/src/firebolt/client/client.py#L3
> build: Limit anyio version

- setup.cfg
- src/firebolt/model/engine.py
- tests/integration/resource_manager/test_engine.py
- tests/unit/service/conftest.py
- tests/unit/service/test_engine.py
Added `engine_type` parameter to `engine.update` to allow changing engine type via resource management api
> feat: Add rm support for engine type update

- setup.cfg
- src/firebolt/client/client.py
Released anyio version and removed the hack, that is not needed anymore. Verified with a dedicated integration test, that we have
> fix: Release anyio version

- src/firebolt/model/engine.py
- src/firebolt/service/engine.py
- src/firebolt/service/types.py
- tests/unit/service/conftest.py
- tests/unit/service/test_engine.py
Some minor resource manager updates for firebolt-cli
- Support passing auto_stop as 0 (don't treat it as empty parameter)
- Support for `Failed` engine state
> fix: Engine service improvements

- tests/integration/dbapi/async/test_queries_async.py
- tests/integration/dbapi/conftest.py
- tests/integration/dbapi/sync/test_queries.py
- tests/integration/dbapi/sync/test_system_engine.py
Porting https://github.com/firebolt-db/firebolt-python-sdk/pull/314 to 0.x
> test: Fix API return values in integration

- src/firebolt/service/database.py
- src/firebolt/service/engine.py
- tests/unit/service/test_database.py
- tests/unit/service/test_engine.py
returned the `get_by_name` methods for database and engine in the new identity
> feat: backward compatibility for get_by_name methods

- docs/requirements.txt
Somehow readthedocs fails to pull the theme on main. Maybe it was once default but later was changed.
Regardless, it doesn't hurt to install it anyway.
Build succeeding now: https://readthedocs.com/projects/firebolt-firebolt-python-sdk-final/builds/1769046/
> build: Fix docs prerequisite

- src/firebolt/client/auth/request_auth_base.py
- tests/unit/client/auth/test_request_auth.py
Extract the user-friendly error message when auth fails
> feat: Improve auth error

- src/firebolt/model/V1/binding.py
- src/firebolt/model/engine.py
- src/firebolt/service/V1/binding.py
- src/firebolt/service/manager.py
- src/firebolt/utils/urls.py
- tests/unit/service/V1/conftest.py
- tests/unit/service/V1/test_bindings.py
- tests/unit/util.py
Airflow uses bindings from V1 of resource manager. This fix is to add those back.
Also adding an Engine stub for type imports in airflow hook.
> fix: Re-adding bindings to resource manager

- setup.cfg
- src/firebolt/async_db/connection.py
- src/firebolt/client/client.py
- src/firebolt/client/http_backend.py
- src/firebolt/common/http_backend.py
- src/firebolt/db/connection.py
- tests/integration/dbapi/async/V1/test_queries_async.py
- tests/integration/dbapi/sync/V1/test_queries.py
- tests/unit/async_db/V1/test_cursor.py
- tests/unit/async_db/V2/test_cursor.py
- tests/unit/client/V1/conftest.py
- tests/unit/client/V1/test_client_async.py
- tests/unit/client/V2/test_client_async.py
- tests/unit/conftest.py
- tests/unit/db/V1/conftest.py
- tests/unit/db/V1/test_cursor.py
- tests/unit/db/V2/test_cursor.py
- tests/unit/db_conftest.py
- tests/unit/response.py
- tests/unit/service/V1/conftest.py
- tests/unit/service/V2/conftest.py
- Relaxed `httpx` minimal version to 0.19. 
- Relased `pytest-httpx` minimal version to 0.13 (corresponds to `httpx==0.19`)
- Update unit test mocks to support a range of pytest-httpx version
> build: Fir 28002 relax httpx version

- src/firebolt/client/auth/base.py
- src/firebolt/utils/util.py
- tests/unit/utils/test_utils.py
Adding a fix described in FIR-29334
Server does not propagate the error even if token expires. This leads to us not refreshing the token when we should have been able to. Until there's a fix on the backend (might take considerable time) we have to try to check in the error body.
> fix: Refresh auth token on 500

- src/firebolt/async_db/cursor.py
- src/firebolt/db/cursor.py
- src/firebolt/utils/util.py
- tests/unit/async_db/V1/test_cursor.py
- tests/unit/async_db/V2/test_cursor.py
- tests/unit/db/V1/test_cursor.py
- tests/unit/db/V2/test_cursor.py
FIR-28748
Currently some error details are hidden in the error body,  which is not shown by default by httpx.raise_for_status(). This code tries to extract that error and print it to error log.
Porting from https://github.com/firebolt-db/firebolt-python-sdk/pull/279
> fix: Log internal error body if present

- tests/integration/dbapi/async/V1/test_queries_async.py
- tests/integration/dbapi/async/V2/test_queries_async.py
- tests/integration/dbapi/sync/V1/test_queries.py
- tests/integration/dbapi/sync/V2/test_queries.py
Removed `CREATE/DELETE JOIN INDEX` queries from integration tests since they're deprecated now
> test: removed join index queries

- src/firebolt/async_db/cursor.py
- src/firebolt/common/base_cursor.py
- src/firebolt/db/cursor.py
- tests/unit/async_db/V1/test_cursor.py
- tests/unit/async_db/V2/test_cursor.py
- tests/unit/db/V1/test_cursor.py
- tests/unit/db/V2/test_cursor.py
FIR-30143
Some set parameters are not allowed. Adding an appropriate error message for them.
> feat: Disallow internal set parameters

- .gitattributes
This setting automatically instructs Git to convert your local line endings to the ones of the repo on commit. This allows us to concentrate on actual changes to the files even if contributors work on Windows systems.
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings
> chore: Standardise line endings

- src/firebolt/async_db/connection.py
- src/firebolt/async_db/cursor.py
- src/firebolt/async_db/util.py
- src/firebolt/client/constants.py
- src/firebolt/common/base_cursor.py
- src/firebolt/common/constants.py
- src/firebolt/db/connection.py
- src/firebolt/db/cursor.py
- src/firebolt/db/util.py
- tests/integration/dbapi/async/V2/conftest.py
- tests/integration/dbapi/async/V2/test_queries_async.py
- tests/integration/dbapi/async/V2/test_system_engine_async.py
- tests/integration/dbapi/sync/V2/conftest.py
- tests/integration/dbapi/sync/V2/test_queries.py
- tests/integration/dbapi/sync/V2/test_system_engine.py
- tests/unit/async_db/V2/conftest.py
- tests/unit/async_db/V2/test_cursor.py
- tests/unit/common/test_base_cursor.py
- tests/unit/conftest.py
- tests/unit/db/V2/conftest.py
- tests/unit/db/V2/test_cursor.py
FIR-30151
Support decoupling of databases and engines (USE DATABASE, USE ENGINES).
Design decisions:
* Connection object holds initial database/engine that's specified by the user. All cursors created from it inherit these, but also keep them local. This means that cursors change on execution of "USE DATABASE/ENGINE" where they're connected to, but any new cursors from a connection will start from the initial configuration.
* `init_parameters` in connection used for parameters that server side returns from USE command. On connect() we execute these queries on system engine if the user supplied database/engine and pass the resulting parameters to the Connection constructor. This ensures connection is initialised as per user parameters.
* ENGINE_STATUS is now a list, since engines V2 and …
> feat: Use engine support

- src/firebolt/model/V2/database.py
- tests/unit/service/V2/test_database.py
FIR-30871
`ALTER DATABASE x WITH` has been changed to `ALTER DATABASE x SET`
Reflecting this in code and adding missing tests.
> chore: Update alter database syntax

- tests/integration/dbapi/async/V2/conftest.py
- tests/integration/dbapi/async/V2/test_queries_async.py
- tests/integration/dbapi/async/V2/test_system_engine_async.py
- tests/integration/dbapi/sync/V2/conftest.py
- tests/integration/dbapi/sync/V2/test_queries.py
- tests/integration/dbapi/sync/V2/test_system_engine.py
Some dbs were not cleaned up.
Reusing existing fixtures that cleanup the dbs automatically.
> test: Fix cleanup on v2

- tests/integration/dbapi/async/V2/test_queries_async.py
- tests/integration/dbapi/sync/V2/test_queries.py
As Firebolt has improved our "long" tests became too fast. Making them slower so they test the timeout again.
> test: Increase long test execution

- tests/integration/dbapi/async/V2/test_system_engine_async.py
- tests/integration/dbapi/sync/V2/test_system_engine.py
System engine on V2 now supports create table statement. Adjusting the test.
> test: fix system engine tests

- src/firebolt/async_db/connection.py
- src/firebolt/async_db/cursor.py
- src/firebolt/async_db/util.py
- src/firebolt/common/base_cursor.py
- src/firebolt/db/connection.py
- src/firebolt/db/cursor.py
- src/firebolt/db/util.py
- src/firebolt/utils/util.py
- tests/unit/async_db/V1/test_cursor.py
- tests/unit/async_db/V2/test_cursor.py
- tests/unit/db/V1/test_cursor.py
- tests/unit/db/V2/test_cursor.py
- tests/unit/utils/test_utils.py
FIR-31838
Let backend add account_id to system engine when it's needed.
> fix: account_id handling for system engine in v2

- tests/integration/dbapi/async/V2/conftest.py
- tests/integration/dbapi/async/V2/test_system_engine_async.py
- tests/integration/dbapi/sync/V2/test_system_engine.py
CREATE TABLE works on FB 1.0 and 2.0 engines v2, but not on 2.0 engines v2.
Either way we'll fail on CREATE or INSERT statement when running on system engine so I'm modifying the test to reflect that.
Also fixing DESCRIPTION clause in fixture.
> test: Fix SA engine check

- tests/integration/resource_manager/V2/test_database.py
This test is temporarily skipped since the underlying function is disabled in engines v1. Will revisit this later.
> test: Skip databases get_many

- setup.cfg
- src/firebolt/service/V1/engine.py
- tests/integration/resource_manager/V1/test_engine.py
- tests/unit/service/V1/conftest.py
- tests/unit/service/V1/test_engine.py
get_many is missing since the version merge. Adding it as there might still be some use cases that rely on this.
Docs also mention this function.
Setting mypy to < 1.10.0 since the new version introduces errors outside of the scope of this change.
> fix: Readd get_many for old engines

- tests/integration/resource_manager/V2/conftest.py
During nightlies some of the engine names became to long (>61 characters). This change avoids appending too much at the end.
e.g. https://github.com/firebolt-db/firebolt-python-sdk/actions/runs/8826365388/job/24231982381
> ci: Decrease engine name length

- src/firebolt/model/V2/engine.py
In order to execute engine start/stop commands we no longer need to verify the engine we're running is attached to a database since we're running against system engine.
> fix: Engine running check in RM

- tests/integration/dbapi/async/V2/conftest.py
- tests/integration/dbapi/sync/V2/conftest.py
> test: Fix sa character limit in tests

- setup.cfg
We recently an issue where running many async queries at the same time would cause a DNS resolution error. This was specifically due to a thread used by one of the dependencies being overloaded.
Upgrading httpcore seems to solve this so increasing the lower limit for it in our setup.cfg.
> build: lower limit httpcore to a stable version

- tests/integration/dbapi/async/V2/conftest.py
- tests/integration/dbapi/sync/V2/conftest.py
Since service account can be upper case we should quote it. It's unquoted in destruction SQL so it was erroring our integration tests/nightlies.
> test: Fix service account deletion

- .github/workflows/integration-tests-v1.yml
- .github/workflows/integration-tests-v2.yml
- .github/workflows/integration-tests.yml
- src/firebolt/async_db/connection.py
- src/firebolt/db/connection.py
- src/firebolt/model/V2/database.py
- src/firebolt/model/V2/engine.py
- src/firebolt/service/V2/base.py
- src/firebolt/service/V2/database.py
- src/firebolt/service/V2/engine.py
- tests/integration/conftest.py
- tests/integration/dbapi/async/V1/test_queries_async.py
- tests/integration/dbapi/async/V2/conftest.py
- tests/integration/dbapi/async/V2/test_errors_async.py
- tests/integration/dbapi/async/V2/test_queries_async.py
- tests/integration/dbapi/async/V2/test_system_engine_async.py
- tests/integration/dbapi/conftest.py
- tests/integration/dbapi/sync/V1/test_queries.py
- tests/integration/dbapi/sync/V1/test_system_engine.py
- tests/integration/dbapi/sync/V2/conftest.py
- tests/integration/dbapi/sync/V2/test_errors.py
- tests/integration/dbapi/sync/V2/test_queries.py
- tests/integration/dbapi/sync/V2/test_system_engine.py
- tests/integration/resource_manager/V2/test_database.py
- tests/integration/resource_manager/V2/test_engine.py
- tests/unit/service/V2/conftest.py
- tests/unit/service/V2/test_engine.py
Created a separate integration testing workflow to run a full integration test suite on account v2. Made some fixes and improvements (mainly to resource management) to make sure tests are passing
> test: Integration testing account v2

- src/firebolt/async_db/connection.py
- src/firebolt/async_db/util.py
- src/firebolt/client/client.py
- src/firebolt/common/_types.py
- src/firebolt/common/cache.py
- src/firebolt/db/connection.py
- src/firebolt/db/util.py
- src/firebolt/utils/util.py
- tests/unit/async_db/V2/test_connection.py
- tests/unit/conftest.py
- tests/unit/db/V2/test_connection.py
FIR-33386
I had to create our own cache class since the standard `lru_cache` has issues, namely:
* Does not work well with async
* Does not work well with Trino specifically
> feat: Caching URL and account info

- src/firebolt/async_db/cursor.py
- src/firebolt/db/cursor.py
- tests/unit/common/test_token_storage.py
os.path was not a good idea since on windows it uses different slashes. As I understand it's primary use is to resolve system paths instead of URL. 
Changed to urljoin, which seems to be the recommended solution. Test run [succeeds](https://github.com/firebolt-db/firebolt-python-sdk/actions/runs/9811623994).
The "/" trick we're doing is necessary at least to be compatible with the previous code. Our tests expect the url to have the trailing slash even if there's nothing after it (or just query parameters).
> fix(FIR-34234): windows-compatible url parsing

- .github/workflows/integration-tests-v2.yml
This lets us run centralised tests from the ecosystem CI repo.
> ci: Allow calling tests from another repo

- src/firebolt/async_db/connection.py
- src/firebolt/async_db/cursor.py
- src/firebolt/client/client.py
- src/firebolt/common/cache.py
- src/firebolt/db/connection.py
- src/firebolt/db/cursor.py
- src/firebolt/utils/urls.py
- tests/integration/dbapi/async/V2/test_system_engine_async.py
- tests/integration/dbapi/sync/V2/test_system_engine.py
- tests/unit/V1/client/conftest.py
- tests/unit/V1/client/test_client.py
- tests/unit/V1/client/test_client_async.py
- tests/unit/V1/conftest.py
- tests/unit/V1/service/conftest.py
- tests/unit/async_db/test_connection.py
- tests/unit/client/test_client.py
- tests/unit/client/test_client_async.py
- tests/unit/conftest.py
- tests/unit/db/test_connection.py
- tests/unit/db_conftest.py
- tests/unit/service/test_resource_manager.py
- Removed usage of v2 `account/<account>/resolve` endpoint
- Removed usages v2 account id and account version
> refactor: FIR-35468 remove account resolve endpoint from python sdk

- docsrc/Connecting_and_queries.rst
> docs: Missing comma in connection example using dotenv

- .github/workflows/build-documentation.yml
- README.md
`python-sdk.docs.firebolt.io` is hosted on readthedocs, which we're not using anymore as it's not being rebuilt. Currently the docs are auto deployed at `old.docs.firebolt.io` due to the org rules. We'll change this separately.
> chore: Fix doc link in readme

- src/firebolt/common/_types.py
- tests/unit/common/test_typing_parse.py
Fixed support for column names with spaces in structs
> fix: Fir 38125 ecosystem support for struct type for python sdk

- src/firebolt/async_db/__init__.py
- src/firebolt/db/__init__.py
When using Array with typehints we run into mypy issues since ExtendedType is larger than a subset of it. e.g. a connector that does not yet have support for struct tries to define array element typehint as Union[type, Decimal, Array] but receives an error since it's actually an Extended type.
> fix: Expose extended type via standard dbapi import

- docsrc/Connecting_and_queries.rst
- src/firebolt/async_db/connection.py
- src/firebolt/async_db/cursor.py
- src/firebolt/client/constants.py
- src/firebolt/common/base_connection.py
- src/firebolt/common/base_cursor.py
- src/firebolt/db/connection.py
- src/firebolt/db/cursor.py
- src/firebolt/utils/exception.py
- src/firebolt/utils/util.py
- tests/integration/dbapi/async/V2/conftest.py
- tests/integration/dbapi/async/V2/test_server_async.py
- tests/integration/dbapi/sync/V2/conftest.py
- tests/integration/dbapi/sync/V2/test_server_async.py
- tests/unit/V1/async_db/test_cursor.py
- tests/unit/V1/db/test_cursor.py
- tests/unit/async_db/test_connection.py
- tests/unit/async_db/test_cursor.py
- tests/unit/db/test_connection.py
- tests/unit/db/test_cursor.py
- tests/unit/db_conftest.py
Following the design doc in https://docs.google.com/document/d/1KfFxCgDxeqyll9dth10QfpUVKjo-aX7yL4Mwn00CZps/
> feat(FIR-42854): Server side async query execution

- docsrc/Connecting_and_queries.rst
cursor.fetchall() example was written twice in docs
> docs: remove docs repetition

- docsrc/Connecting_and_queries.rst
- src/firebolt/async_db/connection.py
- src/firebolt/common/base_connection.py
- src/firebolt/db/connection.py
- tests/integration/dbapi/async/V2/test_server_async.py
- tests/integration/dbapi/sync/V2/test_server_async.py
- tests/unit/async_db/test_connection.py
- tests/unit/db/test_connection.py
- tests/unit/db_conftest.py
This allows seamlessly cancel a running query
> feat(FIR-43324): async cancellation method

- .github/workflows/code-check.yml
Pre-commit is using deprecated caching action and that action is no longer maintained. Instead a simple run command is used to run pre-commit checks.
Example [failure](https://github.com/firebolt-db/firebolt-python-sdk/actions/runs/14528967276/job/40783760962).
> ci(NoTicket): Fix pre commit

- src/firebolt/common/_types.py
- tests/unit/common/test_typing_parse.py
There's an issue exclusively for Firebolt 1.0 where decimal is returned as float, but we're parsing it incorrectly.
Parsing it into a string first keeps the correct precision.
> fix(NoTicket): Decimal parsing from float

- src/firebolt/common/_types.py
- src/firebolt/common/row_set/streaming_common.py
- src/firebolt/common/row_set/synchronous/in_memory.py
- tests/integration/dbapi/async/V1/conftest.py
- tests/integration/dbapi/async/V1/test_queries_async.py
- tests/integration/dbapi/sync/V1/conftest.py
- tests/integration/dbapi/sync/V1/test_queries.py
- tests/unit/common/row_set/asynchronous/test_in_memory.py
- tests/unit/common/row_set/asynchronous/test_streaming.py
- tests/unit/common/row_set/conftest.py
- tests/unit/common/row_set/synchronous/test_in_memory.py
- tests/unit/common/row_set/synchronous/test_streaming.py
- tests/unit/common/test_typing_parse.py
Fixing decimal parsing again. `json.loads` does not parse decimal if it's not quoted, since it breaks JSON convention. The value returned is truncated. I'm porting back a fix we had before streaming that does not parse float on `json.loads` and lets the rest of the parsing code handle it.
A bunch of tests to verify this in different scenarios.
> fix(NoTicket): better decimal parsing and testing

- src/firebolt/common/cursor/base_cursor.py
To avoid confusion and accidental usage of cursor.query_id, marking it as deprecated.
> chore(FIR-42243): Mark cursor.query_id as not populated in docstring

- docsrc/Connecting_and_queries.rst
- src/firebolt/async_db/connection.py
- src/firebolt/common/base_connection.py
- src/firebolt/db/connection.py
- tests/integration/dbapi/async/V2/test_server_async.py
- tests/integration/dbapi/sync/V2/test_server_async.py
- tests/unit/async_db/test_connection.py
- tests/unit/db/test_connection.py
- tests/unit/db_conftest.py
Initially proposed in https://github.com/firebolt-db/firebolt-python-sdk/pull/430
Exposing `get_async_query_info` method that allows users to easily access additional information about their async query: status, error message, query id, etc.
This includes refactoring to future-proof this method as multiple queries might correspond to a single async token.
> feat(FIR-45961): expose async query info method

- .github/workflows/integration-tests-core.yml
- .github/workflows/nightly-v1.yml
- .github/workflows/nightly-v2.yml
Fix nightlies regular tests to not run core tests and add core workflow call.
There's no windows image compiled so skipping it in the matrix.
MacOS does not have docker installed by default. Fixing this might take some effort so skipping it for now.
> ci(NoTicket): Add core tests to nightlies

- docsrc/Connecting_and_queries.rst
Add missing documentation for paramstyle setting
> docs(FIR-44268): add documentation for paramstyle

- tests/integration/dbapi/async/V2/test_queries_async.py
- tests/integration/dbapi/conftest.py
- tests/integration/dbapi/sync/V2/test_queries.py
- tests/unit/common/test_typing_parse.py
Added unit and integration tests for large decimal and bigint values, which are returned as strings in the json format
> test(FIR-34592): add quoted decimal and bigint tests

- tests/integration/dbapi/async/V2/test_errors_async.py
- tests/integration/dbapi/sync/V2/test_errors.py
A change on the backend causes some caching to kick in and return a different error when we connect with no user associated with a service account.
> test(FIR-49477): Fix error check for SA with no user

- tests/unit/V1/client/test_client_async.py
- tests/unit/client/test_client_async.py
Giving the event loop a bit more time to switch context seems to resolve the issue.
> test(FIR-47519): fix async falky test
