firebolt-db/firebolt-python-sdk

examples/management.ipynb
src/firebolt/async_db/connection.py
src/firebolt/async_db/cursor.py
src/firebolt/model/database.py
src/firebolt/model/engine.py
src/firebolt/service/binding.py
src/firebolt/service/database.py
src/firebolt/service/engine.py
tests/unit/service/conftest.py
tests/unit/service/test_engine.py

https://packboard.atlassian.net/browse/FIR-8571
https://packboard.atlassian.net/wiki/spaces/PACB/pages/2715779103/Logging
Current proposal is to add logging for various operations at INFO level:
* Engine - Create/Delete/Start/Stop (start includes intermediate startup statuses, so you can see progress in startup duration)
* Database - Create/Delete
* Cursor - run Query (includes query text)
Note: any of this logging can be configured/turned off. See the top of the management.ipynb notebook

add logging

---

.github/workflows/sonar.yml
.gitignore
setup.cfg

Create an action for running SonarCloud code check. Added unit tests run with coverage calculation to add it to report

create sonar check action

---

.github/workflows/sonar.yml

Update coverage calculation path for SonarCube to be able to parse it

fix coverage path

---

.github/workflows/integration-tests.yml
.github/workflows/nightly.yml
tests/integration/dbapi/conftest.py

to allow users of zsh to run integration tests locally.

fix:Changed USERNAME env variable to USER_NAME

---

.github/workflows/release.yml

Automating GitHub release and changelog generation.
Tested execution on a local fork.

ci: Adding GH release and notes

---

.github/workflows/security-scan.yml

fix: change sc and fossa API token names

---

.github/workflows/release.yml

Refactored release action for reuse.

feat: Using shared release action

---

.github/workflows/integration-tests.yml
.github/workflows/nightly.yml

Add ACCOUNT_NAME env variable to test runs

test: fix integration tests

---

.github/workflows/pull-request.yml
.github/workflows/security-scan.yml
.github/workflows/unit-tests.yml
sonar-project.properties

The pipeline fails on the branch, because it depends on the changes, that should be in main

test: Make pytest generate coverage report and sonar read it

---

tests/integration/dbapi/async/test_queries_async.py

fix: Merge errors in tests

---

src/firebolt/async_db/connection.py
src/firebolt/client/auth.py
src/firebolt/common/exception.py
src/firebolt/common/settings.py
src/firebolt/service/manager.py
tests/unit/async_db/test_connection.py
tests/unit/client/conftest.py
tests/unit/client/test_client.py
tests/unit/client/test_client_async.py
tests/unit/common/test_settings.py
tests/unit/conftest.py
tests/unit/db/test_connection.py
tests/unit/service/test_resource_manager.py

Allowing users to use access token for authentication in both `ResourceManager` and dbapi `Connection`.
- Added `Auth.from_token()`
- Added `Settings.access_token`
- Added `access_token` parameter to dbapi `connect` function

feat: Fir 10511 feature request support resour

---

tests/integration/resource_manager/test_engine.py
tests/unit/service/conftest.py

Dev is now using new engine types. This fixes integration tests errors.

test: Fix engine types

---

examples/dbapi.ipynb

docs: fix dbapi examples notebook

---

.github/workflows/code-check.yml
.pre-commit-config.yaml
setup.cfg
src/firebolt/client/auth.py
src/firebolt/client/client.py
src/firebolt/client/resource_manager_hooks.py
src/firebolt/common/exception.py
src/firebolt/common/settings.py
src/firebolt/common/token_storage.py
src/firebolt/common/util.py
tests/unit/client/conftest.py
tests/unit/client/test_auth.py
tests/unit/client/test_auth_async.py
tests/unit/client/test_client.py
tests/unit/client/test_client_async.py
tests/unit/conftest.py

Added new flake8 checkers for docstrings:
- flake8-docstrings - validate that every required object has a docsting.
- flake8-spellcheck - spelling checker for docs
- darglint - validated that docstings have all required items (args, return value, raised exceptions)
Added docstrings for client and common modules. Other modules will be covered in next PRs

docs: Fir 12403 add linter rule requiring docs

---

src/firebolt/common/exception.py
src/firebolt/common/token_storage.py
src/firebolt/common/urls.py
src/firebolt/common/util.py

Added mock modules to `firebolt.common` to have backward compatible imports

fix: Fir 13884 fix import backward compatibil

---

setup.cfg
src/firebolt/client/client.py

This finally fixes the vulnerability in httpx

chore: Upgrade httpx version

---

src/firebolt/async_db/cursor.py
tests/unit/async_db/test_cursor.py
tests/unit/db_conftest.py

add statistics information returned by the backend to the cursor

feat: Add statistics property to the cursor

---

src/firebolt/utils/usage_tracker.py
tests/unit/utils/test_usage_tracker.py

It has been decided to classify DBT as a client. Changing tracking accordingly.

refactor: reclassify DBT as client for tracking

---

src/firebolt/utils/usage_tracker.py
tests/unit/utils/test_usage_tracker.py

Signatures extracted from the source code of relevant clients.

chore: Adding more client detection

---

.github/workflows/integration-tests.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
src/firebolt/client/auth/__init__.py
src/firebolt/client/auth/request_auth_base.py
src/firebolt/client/auth/service_account.py
src/firebolt/client/auth/username_password.py
src/firebolt/utils/urls.py
tests/integration/conftest.py
tests/integration/dbapi/async/conftest.py
tests/integration/dbapi/async/test_auth_async.py
tests/integration/dbapi/sync/conftest.py
tests/integration/dbapi/sync/test_auth.py
tests/unit/client/auth/test_request_auth.py
tests/unit/client/conftest.py

Initially proposed in https://github.com/firebolt-db/firebolt-python-sdk/pull/209

feat: Service account authentication

---

.github/workflows/integration-tests.yml
.github/workflows/nightly.yml

Since dev service account is broken switching to staging for now.
Confirmed working by running integration test workflow on this branch.

ci: Switching to staging

---

.github/workflows/nightly-workflow.yml
.github/workflows/unit-tests.yml

This allows us to monitor test performance over time in Foresight.

ci: Add foresight test analysis

---

src/firebolt/async_db/cursor.py

Finally add docstring for a flush_parameters cursor method we can close that long going Jira ticket

docs: finally add docstring for flush_parameters cursor method

---

setup.cfg

Updated httpx version to `0.24.0`. Tests seem to be fine, no visible issues

build: update httpx version

---

setup.cfg
src/firebolt/async_db/connection.py
src/firebolt/db/connection.py

fixed the imports from httpcore so it will be compatible for 0.17.3 version

fix: compatibility with httpcore 0.17.3

---

src/firebolt/async_db/cursor.py
src/firebolt/db/cursor.py

added an error body when there is an unfamiliar error that has some info in it

feat: show error body

---

.readthedocs.yaml

This along with the webhook changes fixes auto doc build

build: Update readthedocs config

---

docs/requirements.txt

build: Unify doc and build requirements

---

tests/integration/dbapi/async/test_queries_async.py
tests/integration/dbapi/conftest.py
tests/integration/dbapi/sync/test_queries.py

Fixing some integration tests
Passing on staging: https://github.com/firebolt-db/firebolt-python-sdk/actions/runs/6170243337
Dev is failing due to 502 now: https://github.com/firebolt-db/firebolt-python-sdk/actions/runs/6170241584

test: Fix integration tests before release

---

README.md

Added a lower limit for 1.* python sdk version

docs: pip install lower version limit

---

README.md

Added an upper limit for 0.* python sdk version

docs: pip install upper version limit

---

.readthedocs.yaml
docs/requirements.txt

readthedocs has migrated to a new config file. Merging this from main.

build: Fix readthedocs config

---

docsrc/Connecting_and_queries.rst

Added missing account_name parameters in connection examples

docs: add missing account_name

---

docsrc/Connecting_and_queries.rst
docsrc/Managing_resources.rst

Added some of the missing sections on async.
Updated the auth to suggest Settings is deprecated.
Removed some of the missing engine functions.
We had a mix of tabs and spaces so I've converted everything to spaces.

docs: Update to reflect the current state of the code

---

src/firebolt/model/V2/engine.py
src/firebolt/service/V2/types.py
tests/unit/service/V2/test_engine.py

Added support for `Deleting` status for FB2.0 engines service

feat: add deleting status support

---

src/firebolt/service/V2/engine.py
tests/integration/resource_manager/V2/test_engine.py
tests/unit/service/V2/test_engine.py

Fixed parameters formatting for FB2.0 engines service

fix: Fir 27986 engine parameters formatting

---

.github/workflows/integration-tests-v1.yml
.github/workflows/integration-tests-v2.yml
.github/workflows/integration-tests.yml
.github/workflows/nightly-v2.yml
.github/workflows/release.yml

Removed `environment` parameter from all CI jobs, and set `staging` as a default env

ci: remove env parameter from ci

---

src/firebolt/utils/urls.py

Uncovered in FIR-29931
Despite not being the cause of the issue it's still confusing so I'm removing the duplication.

refactor: Remove duplicate urls

---

src/firebolt/async_db/connection.py
src/firebolt/async_db/util.py
src/firebolt/client/http_backend.py
src/firebolt/common/constants.py
src/firebolt/common/settings.py
src/firebolt/db/connection.py
src/firebolt/db/util.py
tests/unit/common/test_exceptions.py

Fixed cyclic import error when importing `FireboltError` from `firebolt.common.exceptions`

fix: resolve cyclic dependency

---

.github/workflows/integration-tests-v1.yml
.github/workflows/integration-tests-v2.yml
.github/workflows/nightly-v1.yml
.github/workflows/nightly-v2.yml
.github/workflows/unit-tests.yml
README.md
docsrc/index.rst
setup.cfg

- Removed python 3.7 mention from supported versions
- Updated ci to use 3.8 version

ci: Fir 29856 remove python 3 7 support from python sdk

---

README.md
docsrc/Connecting_and_queries.rst

docs: Add disallowed parameters in the readme

---

.github/workflows/integration-tests.yml

ci: Decorate commit with integration test results

---

tests/integration/dbapi/async/V1/test_queries_async.py
tests/integration/dbapi/async/V2/test_queries_async.py
tests/integration/dbapi/sync/V1/test_queries.py
tests/integration/dbapi/sync/V2/test_queries.py

Update aggregating index create statement to fix the test

test: update aggregating index create

---

CONTRIBUTING.MD

Removing no longer relevant links and updating rest api reference. Originally started in #226

docs: Fix links in CONTRIBUTING.MD

---

src/firebolt/async_db/connection.py
src/firebolt/db/connection.py
src/firebolt/model/V2/database.py
src/firebolt/model/V2/engine.py
src/firebolt/service/V2/database.py
src/firebolt/service/V2/engine.py
tests/integration/dbapi/async/V1/test_queries_async.py
tests/integration/dbapi/async/V2/conftest.py
tests/integration/dbapi/async/V2/test_queries_async.py
tests/integration/dbapi/async/V2/test_system_engine_async.py
tests/integration/dbapi/conftest.py
tests/integration/dbapi/sync/V1/test_queries.py
tests/integration/dbapi/sync/V1/test_system_engine.py
tests/integration/dbapi/sync/V2/conftest.py
tests/integration/dbapi/sync/V2/test_queries.py
tests/integration/dbapi/sync/V2/test_system_engine.py
tests/unit/service/V2/test_engine.py

refactor: Use quoting for identifiers

---

src/firebolt/async_db/cursor.py
src/firebolt/db/cursor.py
src/firebolt/utils/exception.py
src/firebolt/utils/util.py
tests/integration/dbapi/async/V2/test_errors_async.py
tests/integration/dbapi/sync/V2/test_errors.py
tests/unit/utils/test_errors.py

feat(FIR-33626): Parsing structured error from response body

---

tests/integration/dbapi/async/V2/conftest.py
tests/integration/dbapi/sync/V2/conftest.py

This fix is needed for nightlies to successfully pass.

test: Fix sa name to be under 63 chars

---

setup.cfg
src/firebolt/client/auth/base.py
src/firebolt/common/_types.py
tests/integration/dbapi/async/V2/test_errors_async.py
tests/integration/dbapi/async/V2/test_queries_async.py
tests/integration/dbapi/async/V2/test_system_engine_async.py
tests/integration/dbapi/conftest.py
tests/integration/dbapi/sync/V2/test_errors.py
tests/integration/dbapi/sync/V2/test_queries.py
tests/integration/dbapi/sync/V2/test_system_engine.py
tests/unit/db_conftest.py

- Added support for geography type
- Simplified errors testing in integration tests

feat: FIR-38073 ecosystem support for geography type for python sdk

---

src/firebolt/async_db/__init__.py
src/firebolt/common/_types.py
src/firebolt/db/__init__.py
tests/integration/dbapi/async/V2/test_queries_async.py
tests/integration/dbapi/conftest.py
tests/integration/dbapi/sync/V2/test_queries.py
tests/unit/common/test_typing_parse.py
tests/unit/db_conftest.py

feat: FIR-38125 ecosystem support for struct type for python sdk

---

src/firebolt/async_db/cursor.py
src/firebolt/common/base_cursor.py
src/firebolt/db/cursor.py
src/firebolt/utils/exception.py
src/firebolt/utils/timeout_controller.py
tests/integration/dbapi/async/V1/test_queries_async.py
tests/integration/dbapi/async/V2/test_queries_async.py
tests/integration/dbapi/async/V2/test_system_engine_async.py
tests/integration/dbapi/async/V2/test_timeout.py
tests/integration/dbapi/conftest.py
tests/integration/dbapi/sync/V1/test_queries.py
tests/integration/dbapi/sync/V2/test_queries.py
tests/integration/dbapi/sync/V2/test_system_engine.py
tests/integration/dbapi/sync/V2/test_timeout.py
tests/unit/V1/db/test_cursor.py
tests/unit/async_db/test_cursor.py
tests/unit/db/test_cursor.py
tests/unit/db_conftest.py
tests/unit/utils/test_timeout_controller.py

Added timeout_seconds parameter to cursor.execute.

feat: FIR-42242 allow setting query timeout in python sdk

---

examples/dbapi.ipynb

Fixed dbapi examples notebook to work on GitHub preview

docs: NoTicket fix dbapi examples notebook

---

.github/dependabot.yml

Added dependably.yml to enable it to automatically update packaged when needed

ci(NoTicket): Enable dependabot automatic updates
